# Generated by Django 2.1 on 2018-10-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('post_user', models.IntegerField()),
                ('current_user', models.IntegerField()),
                ('phone', models.IntegerField(default=123456)),
                ('email_add', models.EmailField(max_length=254)),
                ('messages', models.CharField(max_length=400)),
            ],
        ),
    ]
