# Generated by Django 2.1 on 2018-10-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default='')),
                ('city', models.CharField(default='', max_length=64)),
                ('community', models.TextField()),
                ('address', models.TextField()),
                ('property', models.TextField()),
                ('type', models.TextField()),
                ('area', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('expectmoney', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone', models.IntegerField(default=123456)),
                ('description', models.TextField(default='')),
                ('img', models.TextField(default='')),
            ],
        ),
    ]
